START = "START COMMAND TEXT"
DW_Progress = "Downloading file in progress. If you want to cancel current progress hit cancel button."
Upload_Progress = "Uploading to external host.. please wait few time.."
Uploaded = "Link generated. Filename: {} Size: {} Link: {}"
time_wait = "I can't handle too much file at a time. Please send one file at a time. You can send a file every 10 seconds. Time left: {} seconds."
